export const timezones = [
  "Africa/Dakar",
  "Africa/Johannesburg",
  "America/Bogota",
  "America/Buenos_Aires",
  "America/Los_Angeles",
  "America/New_York",
  "Antarctica/South_Pole",
  "Asia/Bangkok",
  "Asia/Qatar",
  "Asia/Singapore",
  "Australia/Brisbane",
  "Europe/Amsterdam",
  "Europe/London",
  "Pacific/Guam",
];
